# Generated by Django 3.2 on 2022-10-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], max_length=255)),
                ('by', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('dead', models.BooleanField(default=False, null=True)),
                ('kids', models.JSONField(default=list)),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(null=True)),
                ('descendants', models.PositiveIntegerField(null=True)),
                ('parts', models.JSONField(default=list)),
                ('parents', models.IntegerField(null=True)),
                ('reference_id', models.IntegerField(null=True)),
            ],
        ),
    ]
