# Generated by Django 3.2 on 2022-10-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_parents_item_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descendants',
            field=models.IntegerField(null=True),
        ),
    ]
