# Generated by Django 3.2 on 2022-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221026_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
